# Generated by Django 5.2.4 on 2025-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
