# Generated by Django 5.2.4 on 2025-08-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="songs",
            old_name="published_time",
            new_name="publishedTime",
        ),
        migrations.RenameField(
            model_name="songs",
            old_name="rich_thumbnail",
            new_name="richThumbnail",
        ),
    ]
