# Generated by Django 5.2.4 on 2025-08-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_published_time_songs_publishedtime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="songs",
            old_name="view_count",
            new_name="viewCount",
        ),
    ]
