# Generated by Django 5.2.4 on 2025-07-24 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("published_time", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                ("view_count", models.BigIntegerField()),
                ("link", models.URLField()),
                ("thumbnails", models.JSONField()),
                ("rich_thumbnail", models.JSONField(blank=True, null=True)),
                ("channel", models.JSONField()),
                ("accessibility", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "joined_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="api.songs"
                    ),
                ),
            ],
        ),
    ]
