# Generated by Django 5.2.4 on 2025-07-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_songs_playlists"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlists",
            old_name="name",
            new_name="playlistName",
        ),
    ]
