# Generated by Django 5.2.4 on 2025-08-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_name_playlists_playlistname"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlists",
            name="isGlobal",
            field=models.BooleanField(default=False),
        ),
    ]
