name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on VPS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create app directory on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@${{ secrets.VPS_HOST }} "mkdir -p /home/administrator/playfi-app"

      - name: Copy source code to VPS
        run: |
          rsync -avz --delete -e "sshpass -p '${{ secrets.VPS_PASSWORD }}' ssh -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='.vscode' \
            --exclude='app/' \
            --exclude='worker/' \
            --exclude='docker/' \
            ./ \
            administrator@${{ secrets.VPS_HOST }}:/home/administrator/playfi-app/

      - name: Create .env file on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@${{ secrets.VPS_HOST }} \
          "printf '%s\n' '${{ secrets.ENV_FILE }}' > /home/administrator/playfi-app/primary-backend/.env"

      - name: Install dependencies and run migrations on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/administrator/playfi-app/primary-backend

            # Create virtual environment if not exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Upgrade pip inside venv
            source venv/bin/activate
            pip install --upgrade pip

            # Install requirements
            pip install -r requirements.txt

            # Run migrations using venv Python
            python manage.py makemigrations
            python manage.py migrate
          EOF


      - name: Start Django backend with PM2 on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/administrator/playfi-app/primary-backend

            # Use venv Python for uvicorn
            source venv/bin/activate

            # PM2 process
            pm2 delete playfi-django-backend || true
            pm2 start "uvicorn core.asgi:application --host 0.0.0.0 --port 7095" --name playfi-django-backend
            pm2 save
            pm2 startup systemd -u administrator --hp /home/administrator || true
          EOF
